export default [
  {
    id: 'net.slideshare.Pannier',
    name: 'Gingerale - Schweppes, 355 Ml',
    price: 5514,
    available: false,
    rating: 0.6,
  },
  {
    id: 'com.twitpic.Wrapsafe',
    name: 'Pasta - Agnolotti - Butternut',
    price: 9657,
    available: false,
    rating: 2.1,
  },
  {
    id: 'com.reverbnation.Asoka',
    name: 'Oxtail - Cut',
    price: 5899,
    available: false,
    rating: 1.5,
  },
  {
    id: 'com.ezinearticles.Wrapsafe',
    name: 'Beans - Green',
    price: 3273,
    available: false,
    rating: 4.4,
  },
  {
    id: 'de.1und1.Fixflex',
    name: 'Wine - White, Pinot Grigio',
    price: 4981,
    available: true,
    rating: 0.0,
  },
  {
    id: 'com.twitter.Zaam-Dox',
    name: 'Fenngreek Seed',
    price: 5005,
    available: true,
    rating: 4.7,
  },
  {
    id: 'com.cargocollective.It',
    name: 'Juice - Apple, 1.36l',
    price: 5350,
    available: false,
    rating: 3.1,
  },
  {
    id: 'org.altervista.Fixflex',
    name: 'Ecolab - Balanced Fusion',
    price: 9005,
    available: false,
    rating: 1.6,
  },
  {
    id: 'com.issuu.Y-Solowarm',
    name: 'Bread - Multigrain',
    price: 5816,
    available: true,
    rating: 4.4,
  },
  {
    id: 'me.flavors.Gembucket',
    name: 'Salmon - Sockeye Raw',
    price: 1306,
    available: true,
    rating: 0.7,
  },
  {
    id: 'com.vistaprint.Andalax',
    name: 'Sauce - Soy Low Sodium - 3.87l',
    price: 9700,
    available: false,
    rating: 0.1,
  },
  {
    id: 'com.comsenz.Opela',
    name: 'Carbonated Water - Wildberry',
    price: 8085,
    available: true,
    rating: 0.4,
  },
  {
    id: 'hk.com.google.Opela',
    name: 'Lamb - Whole, Frozen',
    price: 8838,
    available: true,
    rating: 3.7,
  },
  {
    id: 'com.prnewswire.Fixflex',
    name: 'Piping - Bags Quizna',
    price: 4604,
    available: true,
    rating: 1.0,
  },
  {
    id: 'com.networksolutions.Stronghold',
    name: 'Yogurt - Raspberry, 175 Gr',
    price: 1651,
    available: false,
    rating: 0.8,
  },
  {
    id: 'edu.washington.Solarbreeze',
    name: 'Bar - Sweet And Salty Chocolate',
    price: 1145,
    available: true,
    rating: 3.2,
  },
  {
    id: 'gov.nih.Duobam',
    name: 'Soup - Campbells - Tomato',
    price: 2928,
    available: true,
    rating: 5.0,
  },
  {
    id: 'uk.co.bbc.Job',
    name: 'Bread - Roll, Canadian Dinner',
    price: 1938,
    available: false,
    rating: 2.7,
  },
  {
    id: 'com.fc2.Fix San',
    name: 'Fireball Whisky',
    price: 6469,
    available: false,
    rating: 4.9,
  },
  {
    id: 'jp.jugem.Fix San',
    name: 'Amaretto',
    price: 7966,
    available: true,
    rating: 4.1,
  },
  {
    id: 'com.hubpages.Overhold',
    name: 'Stock - Beef, Brown',
    price: 6350,
    available: true,
    rating: 0.6,
  },
  {
    id: 'com.diigo.Hatity',
    name: 'Vodka - Moskovskaya',
    price: 3153,
    available: true,
    rating: 2.2,
  },
  {
    id: 'cn.360.Stim',
    name: 'Beer - Blue Light',
    price: 7332,
    available: false,
    rating: 1.4,
  },
  {
    id: 'fr.unblog.Konklab',
    name: 'Ice Cream Bar - Oreo Sandwich',
    price: 1839,
    available: true,
    rating: 0.4,
  },
  {
    id: 'gov.hhs.Zoolab',
    name: 'Soup - Base Broth Chix',
    price: 1374,
    available: false,
    rating: 4.6,
  },
  {
    id: 'com.newyorker.Zaam-Dox',
    name: 'Pepper - Chilli Seeds Mild',
    price: 5760,
    available: true,
    rating: 4.6,
  },
  {
    id: 'com.wordpress.Cardguard',
    name: 'Chicken - Whole Roasting',
    price: 6568,
    available: true,
    rating: 4.2,
  },
  {
    id: 'jp.ne.goo.Alphazap',
    name: 'Steampan - Lid For Half Size',
    price: 6696,
    available: true,
    rating: 1.2,
  },
  {
    id: 'gov.nps.Lotstring',
    name: 'Bread - Pumpernickle, Rounds',
    price: 5974,
    available: false,
    rating: 0.2,
  },
  {
    id: 'com.indiegogo.Sub-Ex',
    name: 'Wine - Hardys Bankside Shiraz',
    price: 7233,
    available: false,
    rating: 1.2,
  },
];
